"""Operation-aware automatic failover for Cosmos transaction endpoints."""

from __future__ import annotations

import math
import re
import time
from typing import Literal
from urllib.parse import quote

from pydantic import Field, TypeAdapter, ValidationError

from .errors import AllEndpointsUnavailable, MalformedUpstreamResponse, TransactionNotFound
from .schemas import CosmosTransaction, CosmosTransactionsResponse, StrictModel
from .service_core import SECTION_TTL, _QUERY_FIELD_UNSUPPORTED, _integer, _mapping, _text
from .transactions import normalize_transactions

_TX_SUSPECT_SECONDS = 60.0
_TX_RECENT_BLOCK_WINDOW = 2_000
_TX_HISTORY_WINDOW = 2_000
_TX_HISTORY_EMPTY_HOPS = 8
_TX_HISTORY_WINDOW_TTL = 300.0
_TX_HISTORY_LIVE_TTL = 15.0
_TX_HISTORY_CURSOR_TTL = 60.0
_TX_HISTORY_MAX_WINDOW_PAGE = 10_000
_TX_CURSOR_RE = re.compile(
    r"^v1\.([1-9][0-9]{0,18})\.([1-9][0-9]{0,18})\.([1-9][0-9]{0,4})$"
)


class CosmosTransactionHistoryResponse(StrictModel):
    """Cursor response for safely walking indexed Cosmos transaction history."""

    state: Literal["available", "indexing_unavailable"]
    transactions: list[CosmosTransaction] = Field(max_length=20)
    anchor_height: int | None = Field(default=None, gt=0)
    window_from: int | None = Field(default=None, gt=0)
    window_to: int | None = Field(default=None, gt=0)
    window_page: int | None = Field(default=None, ge=1, le=_TX_HISTORY_MAX_WINDOW_PAGE)
    total_in_window: int | None = Field(default=None, ge=0)
    has_older: bool
    has_newer: bool
    older_cursor: str | None = Field(default=None, max_length=80)
    newer_cursor: str | None = Field(default=None, max_length=80)
    source_host: str | None = Field(default=None, max_length=253)


def _error_text(payload: object) -> str:
    if not isinstance(payload, dict):
        return ""
    return " ".join(str(payload.get(key, "")) for key in ("message", "details", "error"))


def _index_unavailable(payload: object) -> bool:
    text = _error_text(payload).lower()
    return (("tx" in text or "transaction" in text)
            and ("index" in text or "search" in text)
            and any(marker in text for marker in (
                "disabled", "unavailable", "not enabled", "not configured", "no indexer")))


def _event_payload_valid(payload: object, limit: int) -> bool:
    if not isinstance(payload, dict):
        return False
    txs, responses, pagination = (payload.get("txs"), payload.get("tx_responses"),
                                  payload.get("pagination"))
    return (isinstance(txs, list) and isinstance(responses, list)
            and len(txs) == len(responses) and len(txs) <= limit
            and (pagination is None or isinstance(pagination, dict)))


def _encode_history_cursor(anchor: int, upper: int, page: int) -> str:
    """Encode only positions generated by the fixed-size backward window walk."""
    if (type(anchor) is not int or type(upper) is not int or type(page) is not int
            or anchor <= 0 or upper <= 0 or upper > anchor
            or not 1 <= page <= _TX_HISTORY_MAX_WINDOW_PAGE):
        raise ValueError("invalid transaction history cursor")
    if (anchor - upper) % _TX_HISTORY_WINDOW != 0:
        raise ValueError("invalid transaction history cursor")
    return f"v1.{anchor}.{upper}.{page}"


def _decode_history_cursor(cursor: str) -> tuple[int, int, int]:
    if not isinstance(cursor, str) or not 1 <= len(cursor) <= 80:
        raise ValueError("invalid transaction history cursor")
    match = _TX_CURSOR_RE.fullmatch(cursor)
    if match is None:
        raise ValueError("invalid transaction history cursor")
    anchor, upper, page = (int(value) for value in match.groups())
    _encode_history_cursor(anchor, upper, page)
    return anchor, upper, page


class TransactionEndpointPolicyMixin:
    """Keep endpoint health scoped to the operation that actually failed.

    Basic REST/RPC probes still establish chain identity and freshness. This
    layer adds transaction-specific evidence so a fast endpoint that is fine
    for latest-block/status cannot suppress history from another endpoint.
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._tx_operation_suspect_until: dict[tuple[str, str], float] = {}
        self._tx_search_mode: dict[str, str] = {}

    def _operation_clock(self) -> float:
        clock = getattr(getattr(self, "adapter", None), "_clock", None)
        return clock() if callable(clock) else time.monotonic()

    async def _operation_candidates(self, kind: str, operation: str):
        candidates = list(await self.adapter._cached_candidates(kind))
        state = getattr(self, "_tx_operation_suspect_until", None)
        if state is None:
            state = self._tx_operation_suspect_until = {}
        now = self._operation_clock()
        for key, deadline in list(state.items()):
            if deadline <= now:
                state.pop(key, None)
        ordered = sorted(
            enumerate(candidates),
            key=lambda item: ((operation, item[1].endpoint) in state, item[0]),
        )
        return tuple(candidate for _index, candidate in ordered)

    def _mark_operation_suspect(self, operation: str, endpoint: str) -> None:
        state = getattr(self, "_tx_operation_suspect_until", None)
        if state is None:
            state = self._tx_operation_suspect_until = {}
        state[(operation, endpoint)] = self._operation_clock() + _TX_SUSPECT_SECONDS

    def _clear_operation_suspect(self, operation: str, endpoint: str) -> None:
        state = getattr(self, "_tx_operation_suspect_until", None)
        if state is not None:
            state.pop((operation, endpoint), None)

    async def _tx_search_payload(self, candidate, expression: str, page: int, limit: int):
        encoded = quote(expression, safe="")
        modern = (f"/cosmos/tx/v1beta1/txs?query={encoded}&order_by=ORDER_BY_DESC"
                  f"&page={page}&limit={limit}")
        legacy = (f"/cosmos/tx/v1beta1/txs?events={encoded}&order_by=ORDER_BY_DESC"
                  f"&page={page}&limit={limit}")
        modes = getattr(self, "_tx_search_mode", None)
        if modes is None:
            modes = self._tx_search_mode = {}
        if modes.get(candidate.endpoint) == "legacy":
            payload = await self.transport.get_object(
                candidate.endpoint, legacy, accept_error_payload=True)
            return payload, "legacy"
        payload = await self.transport.get_object(
            candidate.endpoint, modern, accept_error_payload=True)
        if _QUERY_FIELD_UNSUPPORTED.search(_error_text(payload)) is None:
            return payload, "modern"
        modes[candidate.endpoint] = "legacy"
        payload = await self.transport.get_object(
            candidate.endpoint, legacy, accept_error_payload=True)
        return payload, "legacy"

    async def _recent_transaction_expression(self) -> str:
        """Bound the compatibility list route to a recent block window."""
        status = await self.adapter.node_status()
        height = getattr(status, "local_height", None)
        if type(height) is not int or height <= 0:
            raise AllEndpointsUnavailable("current chain height unavailable")
        lower = max(1, height - _TX_RECENT_BLOCK_WINDOW + 1)
        return f"tx.height>={lower}"

    async def _transaction_window(self, lower: int, upper: int, page: int, limit: int):
        """Search one immutable, explicitly bounded height window.

        Identical callers share RequestCache single-flight, so many browser
        sessions do not multiply the same upstream tx-index query.
        """
        if (type(lower) is not int or type(upper) is not int or type(page) is not int
                or type(limit) is not int or lower <= 0 or upper < lower
                or upper - lower + 1 > _TX_HISTORY_WINDOW
                or not 1 <= page <= _TX_HISTORY_MAX_WINDOW_PAGE
                or not 1 <= limit <= 20):
            raise ValueError("invalid transaction history window")

        key = (self.definition.transport.network_id, "transaction_search_window",
               (lower, upper, page, limit))

        async def load():
            expression = f"tx.height>={lower} AND tx.height<={upper}"
            candidates = await self._operation_candidates("rest", "tx_search")
            first_empty = None
            empty_endpoints: list[str] = []
            indexing_unavailable = False
            for candidate in candidates:
                try:
                    payload, _mode = await self._tx_search_payload(
                        candidate, expression, page, limit)
                except Exception:
                    continue
                try:
                    rows, total = normalize_transactions(payload, limit)
                except MalformedUpstreamResponse:
                    if _index_unavailable(payload):
                        indexing_unavailable = True
                        self._mark_operation_suspect("tx_search", candidate.endpoint)
                    continue
                response = {
                    "state": "available",
                    "transactions": rows,
                    "total": total,
                    "source_host": self.adapter._host(candidate.endpoint),
                }
                if rows:
                    for endpoint in empty_endpoints:
                        self._mark_operation_suspect("tx_search", endpoint)
                    self._clear_operation_suspect("tx_search", candidate.endpoint)
                    return response
                if first_empty is None:
                    first_empty = response
                empty_endpoints.append(candidate.endpoint)
            if first_empty is not None:
                return first_empty
            if indexing_unavailable:
                return {
                    "state": "indexing_unavailable",
                    "transactions": [],
                    "total": None,
                    "source_host": None,
                }
            raise AllEndpointsUnavailable("transaction history search unavailable")

        return await self.cache.get_or_load(key, _TX_HISTORY_WINDOW_TTL, load)

    async def transactions(self, limit=20, page=1):
        """Compatibility list route, bounded to the recent transaction window."""
        if type(limit) is not int or not 1 <= limit <= 20 or type(page) is not int or not 1 <= page <= 100:
            raise ValueError("invalid transaction page")

        def normalized(endpoint: str, payload: object):
            try:
                rows, total = normalize_transactions(payload, limit)
                candidate = {"state": "available", "transactions": rows, "page": page,
                             "page_size": limit, "total": total,
                             "has_older": page < 100 and total is not None and page * limit < total,
                             "has_newer": page > 1, "source_host": self.adapter._host(endpoint)}
                return TypeAdapter(CosmosTransactionsResponse).validate_python(candidate).model_dump()
            except (MalformedUpstreamResponse, ValidationError):
                return None

        expression = await self._recent_transaction_expression()
        candidates = await self._operation_candidates("rest", "tx_search")
        first_empty = None
        empty_endpoints: list[str] = []
        indexing_unavailable = False
        for candidate in candidates:
            try:
                payload, _mode = await self._tx_search_payload(candidate, expression, page, limit)
            except Exception:
                continue
            response = normalized(candidate.endpoint, payload)
            if response is not None:
                if response["transactions"]:
                    for endpoint in empty_endpoints:
                        self._mark_operation_suspect("tx_search", endpoint)
                    self._clear_operation_suspect("tx_search", candidate.endpoint)
                    return response
                if first_empty is None:
                    first_empty = response
                empty_endpoints.append(candidate.endpoint)
                continue
            if _index_unavailable(payload):
                indexing_unavailable = True
                self._mark_operation_suspect("tx_search", candidate.endpoint)

        if first_empty is not None:
            return first_empty
        if indexing_unavailable:
            return {"state": "indexing_unavailable", "transactions": [], "page": page,
                    "page_size": limit, "total": None, "has_older": False, "has_newer": page > 1}
        raise AllEndpointsUnavailable("no valid transaction search response")

    async def _newer_history_cursor(self, anchor: int, upper: int, page: int,
                                    limit: int) -> str | None:
        """Return the immediately newer transaction page without full-chain search."""
        if page > 1:
            target_page = page - 1
            if upper == anchor and target_page == 1:
                return None
            return _encode_history_cursor(anchor, upper, target_page)
        if upper >= anchor:
            return None

        newer_upper = min(anchor, upper + _TX_HISTORY_WINDOW)
        for _hop in range(_TX_HISTORY_EMPTY_HOPS):
            newer_lower = max(1, newer_upper - _TX_HISTORY_WINDOW + 1)
            probe = await self._transaction_window(newer_lower, newer_upper, 1, 1)
            total = probe.get("total")
            if type(total) is int and total > 0:
                target_page = max(1, math.ceil(total / limit))
                if newer_upper == anchor and target_page == 1:
                    return None
                return _encode_history_cursor(anchor, newer_upper, target_page)
            if probe.get("transactions"):
                if newer_upper == anchor:
                    return None
                return _encode_history_cursor(anchor, newer_upper, 1)
            if newer_upper >= anchor:
                return None
            newer_upper = min(anchor, newer_upper + _TX_HISTORY_WINDOW)

        # Do not turn a Newer click into an unbounded scan on a sparse chain.
        return _encode_history_cursor(anchor, min(anchor, upper + _TX_HISTORY_WINDOW), 1)

    async def _transaction_history_uncached(self, limit: int, cursor: str | None):
        if cursor is None:
            status = await self.adapter.node_status()
            anchor = getattr(status, "local_height", None)
            if type(anchor) is not int or anchor <= 0:
                raise AllEndpointsUnavailable("current chain height unavailable")
            upper, page = anchor, 1
            requested_was_live = True
        else:
            anchor, upper, page = _decode_history_cursor(cursor)
            requested_was_live = False

        first_upper, first_page = upper, page
        response = None
        lower = max(1, upper - _TX_HISTORY_WINDOW + 1)
        batched_older_cursor = None

        for hop in range(_TX_HISTORY_EMPTY_HOPS):
            lower = max(1, upper - _TX_HISTORY_WINDOW + 1)
            response = await self._transaction_window(lower, upper, page, limit)
            if response["state"] == "indexing_unavailable":
                candidate = {
                    "state": "indexing_unavailable",
                    "transactions": [],
                    "anchor_height": anchor,
                    "window_from": lower,
                    "window_to": upper,
                    "window_page": page,
                    "total_in_window": None,
                    "has_older": False,
                    "has_newer": False,
                    "older_cursor": None,
                    "newer_cursor": None,
                    "source_host": None,
                }
                return CosmosTransactionHistoryResponse.model_validate(candidate).model_dump()

            if response["transactions"] or lower == 1:
                break

            next_upper = lower - 1
            if hop == _TX_HISTORY_EMPTY_HOPS - 1:
                batched_older_cursor = _encode_history_cursor(anchor, next_upper, 1)
                break
            upper, page = next_upper, 1

        if response is None:
            raise AllEndpointsUnavailable("transaction history search unavailable")

        rows = response["transactions"]
        total = response.get("total")
        if rows:
            if type(total) is int:
                more_in_window = page * limit < total
            else:
                more_in_window = len(rows) == limit
            if more_in_window and page < _TX_HISTORY_MAX_WINDOW_PAGE:
                older_cursor = _encode_history_cursor(anchor, upper, page + 1)
            elif lower > 1:
                older_cursor = _encode_history_cursor(anchor, lower - 1, 1)
            else:
                older_cursor = None
        elif batched_older_cursor is not None:
            older_cursor = batched_older_cursor
        elif lower > 1:
            older_cursor = _encode_history_cursor(anchor, lower - 1, 1)
        else:
            older_cursor = None

        if requested_was_live and upper == first_upper and page == first_page:
            newer_cursor = None
            has_newer = False
        else:
            newer_cursor = await self._newer_history_cursor(anchor, upper, page, limit)
            has_newer = True

        candidate = {
            "state": "available",
            "transactions": rows,
            "anchor_height": anchor,
            "window_from": lower,
            "window_to": upper,
            "window_page": page,
            "total_in_window": total,
            "has_older": older_cursor is not None,
            "has_newer": has_newer,
            "older_cursor": older_cursor,
            "newer_cursor": newer_cursor,
            "source_host": response.get("source_host"),
        }
        return CosmosTransactionHistoryResponse.model_validate(candidate).model_dump()

    async def transaction_history(self, limit=20, cursor: str | None = None):
        """Cursor through indexed history using only bounded tx-index windows.

        The first page is live. Once the user follows an older cursor, the
        anchor height is frozen into that cursor so newer blocks cannot shift
        the historical walk underneath them.
        """
        if type(limit) is not int or not 1 <= limit <= 20:
            raise ValueError("invalid transaction history limit")
        if cursor is not None:
            _decode_history_cursor(cursor)
        cache_key = (self.definition.transport.network_id, "transaction_history",
                     (limit, cursor or "live"))
        ttl = _TX_HISTORY_LIVE_TTL if cursor is None else _TX_HISTORY_CURSOR_TTL
        return await self.cache.get_or_load(
            cache_key, ttl, lambda: self._transaction_history_uncached(limit, cursor))

    async def transaction_lookup(self, tx_hash: str):
        """Resolve an exact hash without trusting one endpoint's false negative."""
        if not isinstance(tx_hash, str) or re.fullmatch(r"[0-9A-Fa-f]{64}", tx_hash) is None:
            raise ValueError("invalid transaction hash")
        normalized_hash = tx_hash.upper()
        candidates = await self._operation_candidates("rpc", "tx_lookup")
        not_found_endpoints: list[str] = []
        for candidate in candidates:
            try:
                payload = await self.transport.get_object(
                    candidate.endpoint, f"/tx?hash=0x{normalized_hash}&prove=false",
                    accept_error_payload=True)
                error = payload.get("error")
                if isinstance(error, dict):
                    text = str(error.get("data") or error.get("message") or "")
                    if "not found" in text.lower():
                        not_found_endpoints.append(candidate.endpoint)
                    elif _index_unavailable({"message": text}):
                        self._mark_operation_suspect("tx_lookup", candidate.endpoint)
                    continue
                result = _mapping(payload.get("result"), "transaction lookup result")
                result_hash = _text(result.get("hash"), "transaction hash", 64).upper()
                if result_hash != normalized_hash or re.fullmatch(r"[0-9A-F]{64}", result_hash) is None:
                    raise MalformedUpstreamResponse("transaction hash mismatch")
                height = _integer(result.get("height"), "transaction height")
                index = _integer(result.get("index"), "transaction index")
                if height <= 0 or index > 10_000:
                    raise MalformedUpstreamResponse("invalid transaction location")
                for endpoint in not_found_endpoints:
                    self._mark_operation_suspect("tx_lookup", endpoint)
                self._clear_operation_suspect("tx_lookup", candidate.endpoint)
                return {"height": height, "index": index, "tx_hash": result_hash}
            except Exception:
                continue
        if not_found_endpoints:
            raise TransactionNotFound("transaction not found")
        raise AllEndpointsUnavailable("transaction lookup unavailable")

    async def _validator_event_search(self, expression: str, limit: int):
        """Prefer non-empty history while retaining a valid empty fallback."""
        cache_key = (self.definition.transport.network_id, "validator_event_search", (expression, limit))

        async def load():
            candidates = await self._operation_candidates("rest", "tx_search")
            first_empty = None
            empty_endpoints: list[str] = []
            for candidate in candidates:
                try:
                    payload, _mode = await self._tx_search_payload(candidate, expression, 1, limit)
                except Exception:
                    continue
                if _event_payload_valid(payload, limit):
                    if payload["txs"]:
                        for endpoint in empty_endpoints:
                            self._mark_operation_suspect("tx_search", endpoint)
                        self._clear_operation_suspect("tx_search", candidate.endpoint)
                        return payload
                    if first_empty is None:
                        first_empty = payload
                    empty_endpoints.append(candidate.endpoint)
                    continue
                if _index_unavailable(payload):
                    self._mark_operation_suspect("tx_search", candidate.endpoint)
            if first_empty is not None:
                return first_empty
            raise AllEndpointsUnavailable("validator event search unavailable")

        return await self.cache.get_or_load(cache_key, SECTION_TTL, load)
