import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { decodeAccountRouteAddress, findNativeBalance, findOtherBalances, formatAmountString, getAccountDetailView } from '../src/utils/account.js'

const read = (path) => readFileSync(new URL(path, import.meta.url), 'utf8')
const app = read('../src/App.jsx')
const api = read('../src/services/api.js')
const hook = read('../src/hooks/useAccountDetail.js')
const page = read('../src/pages/AccountDetail.jsx')
const validator = read('../src/pages/ValidatorDetail.jsx')
const profile = read('../src/config/networkProfile.js')
const styles = read('../src/styles/app.css')

const address = 'g16mldrfu90pe5r97cjm3xk02m7a3d0z8g9g3r75'

test('account route decoder accepts plain and encoded addresses', () => {
  assert.equal(decodeAccountRouteAddress(address), address)
  assert.equal(decodeAccountRouteAddress(encodeURIComponent(address)), address)
})
test('account route decoder rejects empty, slashes, excessive length, and malformed encoding', () => {
  assert.equal(decodeAccountRouteAddress(''), null)
  assert.equal(decodeAccountRouteAddress('%2F'), null)
  assert.equal(decodeAccountRouteAddress('a'.repeat(129)), null)
  assert.equal(decodeAccountRouteAddress('%E0%A4%A'), null)
})
test('App recognizes account routes with an optional trailing slash', () => {
  assert.match(app, /path\.match\(\/\^\\\/accounts/)
  assert.ok(app.includes('<AccountDetailPage address={accountDetailMatch[1]} />'))
})
test('API client uses the shared request wrapper and encodes the address', () => {
  assert.ok(api.includes('getAccount = (address) => request(`/accounts/${encodeURIComponent(address)}`)'))
  assert.ok(api.includes("error.status = 0"))
})
test('hook maps safe states, supports retry and has no polling timer', () => {
  for (const text of ['requestError.status === 422', 'requestError.status === 503', 'const retry = useCallback', 'requestId === requestIdRef.current']) assert.ok(hook.includes(text))
  assert.equal(hook.includes('setTimeout'), false)
  assert.equal(hook.includes('setInterval'), false)
})
test('hook exposes the safely decoded requested address synchronously', () => {
  assert.ok(hook.includes('const requestedAddress = decodeAccountRouteAddress(routeAddress)'))
  assert.ok(hook.includes('return { ...state, requestedAddress, retry, history, retryHistory, loadMoreHistory }'))
})
test('initial loading renders the account shell with accessible skeletons', () => {
  assert.equal(page.includes('title="Loading account…"'), false)
  for (const text of ['← Back to Overview', 'Account Balance', 'Account Summary', 'Technical details', '<AccountTransactions', 'Loading current account state…']) assert.ok(page.includes(text))
  assert.ok(page.includes("aria-busy={loading ? 'true' : 'false'}"))
  assert.ok(page.includes('account?.address || requestedAddress'))
  assert.ok(page.includes('initialLoading ? <Skeleton'))
  assert.ok(page.includes('aria-hidden="true"'))
  assert.match(styles, /@media \(prefers-reduced-motion: reduce\) \{[^}]*account-detail__placeholder \{ animation: none;/)
  const initialBalance = page.slice(page.indexOf('aria-labelledby="account-balance-title"'), page.indexOf('aria-labelledby="account-summary-title"'))
  assert.ok(initialBalance.indexOf('initialLoading ? <Skeleton') < initialBalance.indexOf('No native bank balance'))
  assert.equal(getAccountDetailView({ account: null, requestedAddress: address, loading: true }), 'loading')
  assert.ok(page.includes("initialLoading ? 'Loading…' : loading ? 'Refreshing…' : 'Refresh'"))
})
test('manual refresh keeps loaded account values visible', () => {
  assert.ok(hook.includes('account: current.account?.address === address ? current.account : null'))
  assert.ok(page.includes("loading ? 'Refreshing…' : 'Refresh'"))
  assert.equal(getAccountDetailView({ account: { found: true }, requestedAddress: address, loading: true }), 'account')
  assert.ok(page.includes('loading && account?.found && <p className="account-detail__updating"'))
})
test('network profile defines the native denom with an ugnot fallback', () => {
  assert.ok(profile.includes('import.meta.env.VITE_NATIVE_DENOM'))
  assert.match(profile, /nativeDenom:\s*publicValue\([\s\S]*?'ugnot'/)
})
test('primary balance selection uses denom rather than a display symbol', () => {
  const synthetic = { denom: 'GNOT', symbol: 'GNOT' }
  const native = { denom: 'ugnot', symbol: 'GNOT' }
  assert.equal(findNativeBalance([synthetic, native], 'ugnot'), native)
  assert.ok(page.includes('findNativeBalance(balances, networkProfile.nativeDenom)'))
  assert.equal(page.includes("balance.symbol === 'GNOT'"), false)
})
test('amount formatter groups integer digits without changing precision', () => {
  assert.equal(formatAmountString('9999999996013'), '9 999 999 996 013')
  assert.equal(formatAmountString('104.600242'), '104.600242')
  assert.equal(formatAmountString('1234567.890123'), '1 234 567.890123')
  assert.equal(formatAmountString('9999999996013000000'), '9 999 999 996 013 000 000')
})
test('missing account refresh reuses retry, preserves content, and reports errors safely', () => {
  assert.equal(getAccountDetailView({ account: { found: false, address }, requestedAddress: address, loading: true }), 'missing')
  assert.ok(page.includes('function MissingAccount({ account, retry, loading, refreshError, history, retryHistory, loadMoreHistory })'))
  assert.ok(page.includes('onClick={retry} disabled={loading}'))
  assert.ok(page.includes("loading ? 'Refreshing…' : 'Refresh'"))
  assert.ok(page.includes('refreshError && <p className="account-detail__refresh-error"'))
  assert.ok(page.includes('<MissingAccount account={account} retry={retry} loading={loading}'))
  assert.ok(page.includes('This address has no account state on the current network.'))
  const missingState = page.slice(page.indexOf('function MissingAccount'), page.indexOf('export function AccountDetail'))
  for (const value of ['sourceLabel(', 'observed_height', 'chain_id', 'Fetched at block']) assert.equal(missingState.includes(value), false)
  assert.ok(missingState.includes('<AccountTransactions'))
  for (const value of ['Account Summary', 'No native bank balance', 'RPC endpoint', 'account-detail__main-balance']) assert.equal(missingState.includes(value), false)
})
test('account view selection preserves safe initial result states', () => {
  assert.equal(getAccountDetailView({ account: null, requestedAddress: null, loading: true }), 'invalid')
  assert.equal(getAccountDetailView({ account: null, requestedAddress: address, invalidAddress: true }), 'invalid')
  assert.equal(getAccountDetailView({ account: null, requestedAddress: address, unavailable: true }), 'unavailable')
  assert.equal(getAccountDetailView({ account: null, requestedAddress: address, error: true }), 'error')
  assert.equal(getAccountDetailView({ account: { found: false }, requestedAddress: address, loading: false }), 'missing')
})
test('page uses a compact balance and account summary overview', () => {
  assert.ok(page.includes('account-detail__overview'))
  assert.ok(page.includes('Account Summary'))
  assert.ok(page.includes('account-detail__main-balance'))
  assert.equal(page.includes('label="Observed Height"'), false)
  const balanceCard = page.slice(page.indexOf('aria-labelledby="account-balance-title"'), page.indexOf('aria-labelledby="account-summary-title"'))
  assert.ok(balanceCard.includes('Account Balance'))
  assert.ok(balanceCard.includes('primary.display_amount'))
  assert.ok(balanceCard.includes('formatAmountString(primary.display_amount)'))
  assert.ok(balanceCard.includes('primary.symbol'))
  for (const label of ['Denom', 'Raw amount', 'Decimals', 'account-detail__compact-list']) assert.equal(balanceCard.includes(label), false)
  const accountSummary = page.slice(page.indexOf('aria-labelledby="account-summary-title"'), page.indexOf('{initialLoading ? <section'))
  for (const value of ['Account number', 'Sequence', 'Denom', 'Decimals', 'Raw amount']) assert.ok(accountSummary.includes(value))
  assert.ok(accountSummary.includes("primary?.amount || '—'"))
  assert.equal(accountSummary.includes('formatAmountString(primary.amount)'), false)
  for (const value of ['RPC endpoint', 'Chain ID', 'Fetched at block', 'observed_height', 'Public key']) assert.equal(accountSummary.includes(value), false)
  assert.ok(styles.includes('grid-template-columns: minmax(240px, .75fr) minmax(0, 1.25fr)'))
  assert.ok(styles.includes('font-size: clamp(24px, 1.8vw, 30px)'))
  const tabletRules = styles.slice(styles.indexOf('@media (max-width: 1050px)'), styles.indexOf('@media (max-width: 760px)', styles.indexOf('@media (max-width: 1050px)')))
  assert.ok(tabletRules.includes('.account-detail__overview { grid-template-columns: 1fr; }'))
  assert.ok(tabletRules.includes('.account-detail__summary-values { grid-template-columns: repeat(3, minmax(0, 1fr)); }'))
  assert.ok(tabletRules.includes('.account-detail__summary-raw { grid-column: span 2; }'))
  assert.match(styles, /@media \(max-width: 760px\)[\s\S]*?account-detail__overview[\s\S]*?grid-template-columns: 1fr/)
  assert.match(styles, /@media \(max-width: 760px\)[\s\S]*?account-detail__summary-values \{ grid-template-columns: repeat\(2, minmax\(0, 1fr\)\); \}[\s\S]*?account-detail__summary-raw \{ grid-column: 1 \/ -1; \}/)
  assert.ok(styles.includes('font-size: 17px; font-weight: 600; overflow-wrap: anywhere'))
})
test('page keeps technical and validator information compact', () => {
  assert.ok(page.includes('<details className="panel account-detail__details">'))
  assert.ok(page.includes('<summary>Technical details</summary>'))
  const technicalDetails = page.slice(page.indexOf('<details className="panel account-detail__details">'), page.indexOf('</details>'))
  for (const label of ['Network', 'RPC endpoint', 'Observed RPC height', 'Public key']) assert.ok(technicalDetails.includes(label))
  for (const label of ['Native balance', 'Raw amount', 'Decimals']) assert.equal(technicalDetails.includes(label), false)
  assert.ok(technicalDetails.includes('CopyValue value={account.public_key.value}'))
  assert.ok(technicalDetails.includes('TechnicalField label="RPC endpoint"'))
  assert.ok(styles.includes('text-align: left; overflow-wrap: anywhere'))
  assert.equal(styles.includes('.account-detail__technical-field > strong { min-width: 0; color: var(--color-text); font-weight: 600; text-align: right'), false)
  assert.equal(styles.includes('.account-detail__technical-field .account-detail__copy-row { justify-content: flex-end; }'), false)
  assert.ok(styles.includes('.account-detail__technical-field .account-detail__copy-row .account-detail__value { min-width: 0; text-align: left; overflow-wrap: anywhere; }'))
  assert.ok(styles.includes('.account-detail__technical-field .account-detail__copy-row .copy-button { flex: 0 0 auto; margin-left: auto; }'))
  assert.ok(styles.includes('.account-detail__technical-grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); }'))
  assert.match(styles, /@media \(max-width: 760px\)[\s\S]*?account-detail__technical-grid \{ grid-template-columns: 1fr/)
})
test('validator relation is a compact message without exposed addresses', () => {
  const validatorCard = page.slice(page.indexOf(': account.validator_relation &&'), page.indexOf('{otherBalances.length > 0'))
  assert.ok(validatorCard.includes('This account belongs to validator'))
  assert.ok(validatorCard.includes('>{account.validator_relation.moniker'))
  assert.ok(validatorCard.includes('/validators/${encodeURIComponent(account.validator_relation.signing_address)}'))
  assert.equal(validatorCard.includes('</a>.</p>'), false)
  assert.equal(validatorCard.includes('View validator'), false)
  assert.equal(validatorCard.includes('operator_address'), false)
  assert.equal(validatorCard.includes('<CopyValue'), false)
})
test('transactions use local paginated history without polling', () => {
  for (const value of ['No indexed transactions found for this account.', 'Outgoing', 'Incoming', 'Self', 'Load more', 'Retry history']) assert.ok(page.includes(value))
  assert.equal(page.includes('Shows locally indexed transactions involving this account.'), false)
  for (const value of ['getAccountTransactions', 'AbortController', 'next_before_height', 'next_before_tx_index']) assert.ok(api.includes(value) || hook.includes(value))
  assert.ok(hook.includes('mergeAccountHistoryItems(current.items'))
  assert.equal(hook.includes('setInterval'), false)
  assert.ok(page.indexOf('<details className="panel account-detail__details">') < page.lastIndexOf('<AccountTransactions'))
})
test('transaction list has one shared header and plain operation and amount columns', () => {
  const transactions = page.slice(page.indexOf('function AccountTransactions'), page.indexOf('function MissingAccount'))
  const header = transactions.slice(transactions.indexOf('account-detail__transaction-header'), transactions.indexOf('{history.items.map'))
  for (const label of ['Type', 'Direction', 'Amount', 'Account', 'Block', 'Tx hash', 'Status']) assert.ok(header.includes(`>${label}</span>`))
  assert.ok(transactions.includes('<span className="account-detail__transaction-operation" data-label="Type">{item.operation}</span>'))
  assert.equal(/<a[^>]*>\{item\.operation\}<\/a>/.test(transactions), false)
  assert.equal(transactions.includes('Send Tokens'), false)
  assert.ok(transactions.includes('className={`account-detail__direction'))
  assert.equal(/<a[^>]*>\{direction\}<\/a>/.test(transactions), false)
  assert.ok(transactions.includes("item.amount != null ? String(item.amount) : '—'"))
  assert.equal(/<a[^>]*>\s*<span className="account-detail__transaction-amount"/.test(transactions), false)
})
test('transaction account, block, and hash columns preserve their links', () => {
  const transactions = page.slice(page.indexOf('function AccountTransactions'), page.indexOf('function MissingAccount'))
  assert.ok(transactions.includes('counterpartyValid ? <a className="account-detail__transaction-counterparty mono"'))
  assert.ok(transactions.includes('item.counterparty !== address'))
  assert.ok(transactions.includes('/^g1[023456789acdefghjklmnpqrstuvwxyz]{38}$/.test(item.counterparty)'))
  assert.ok(transactions.includes('href={`/accounts/${encodeURIComponent(item.counterparty)}`}'))
  assert.ok(transactions.includes("</a> : '—'}</div>"))
  assert.ok(transactions.includes('href={`/blocks/${item.block_height}`}>#{item.block_height}</a>'))
  assert.ok(transactions.includes('className="account-detail__transaction-hash mono" href={`/blocks/${item.block_height}/transactions/${item.index}`}'))
  assert.ok(transactions.includes('title={item.tx_hash} aria-label={`Transaction hash ${item.tx_hash}`}'))
  assert.ok(transactions.includes('{shortHash(item.tx_hash)}'))
  assert.ok(transactions.includes('className="account-detail__transaction-status-slot" data-label="Status" aria-hidden="true"'))
  assert.equal(transactions.includes('<time'), false)
  assert.equal(transactions.includes('item.block_time'), false)
  for (const status of ['Success', 'Failed', 'Pending', 'Unknown']) assert.equal(transactions.includes(status), false)
})
test('transaction headers and rows share desktop columns and become labeled field grids', () => {
  const transactionStyles = styles.slice(styles.indexOf('.account-detail__transaction-list'))
  assert.ok(transactionStyles.includes('--transaction-columns:'))
  assert.ok(transactionStyles.includes('.account-detail__transaction-header, .account-detail__transaction { display: grid; grid-template-columns: var(--transaction-columns)'))
  assert.ok(transactionStyles.includes('minmax(84px, .8fr) 82px minmax(100px, 1fr) minmax(180px, 1.8fr)'))
  assert.ok(transactionStyles.includes('grid-template-columns: var(--transaction-columns); gap: 8px'))
  assert.ok(transactionStyles.includes('.account-detail__transaction-header { padding: 0 12px 2px; color: var(--color-text-secondary); font-size: 10px'))
  assert.ok(transactionStyles.includes('.account-detail__transaction { padding: 10px 12px;'))
  assert.ok(transactionStyles.includes('.account-detail__transaction-amount { color: var(--color-text); font-size: 12px; font-weight: 600; cursor: default; }'))
  for (const className of ['account-detail__transaction-operation', 'account-detail__transaction-counterparty', 'account-detail__transaction-block', 'account-detail__transaction-hash']) assert.ok(transactionStyles.includes(`.${className}`))
  assert.ok(transactionStyles.includes('.account-detail__transaction-counterparty { min-width: 0; color: var(--color-text-bright)'))
  assert.ok(transactionStyles.includes('.account-detail__transaction-block a, .account-detail__transaction-hash { color: var(--color-text-bright); }'))
  assert.equal(transactionStyles.includes('color: var(--color-accent); font-size: 12px; overflow-wrap: anywhere'), false)
  assert.match(transactionStyles, /@media \(max-width: 900px\)[\s\S]*?account-detail__transaction-header \{ display: none; \}/)
  assert.match(transactionStyles, /account-detail__transaction \{ grid-template-columns: repeat\(2, minmax\(0, 1fr\)\)/)
  assert.ok(transactionStyles.includes('content: attr(data-label)'))
  assert.match(transactionStyles, /@media \(max-width: 520px\)[\s\S]*?account-detail__transaction \{ grid-template-columns: minmax\(0, 1fr\); \}/)
  assert.ok(transactionStyles.includes('.account-detail__transaction > * { min-width: 0; }'))
  assert.equal(transactionStyles.includes('font-size: 13px'), false)
  assert.equal(/#[0-9a-f]{3,8}|rgba?\(|hsla?\(/i.test(transactionStyles), false)
})
test('other balances exclude native denom and render only when non-native balances exist', () => {
  const native = { denom: 'ugnot' }
  const other = { denom: 'uatom' }
  assert.deepEqual(findOtherBalances([native, other], 'ugnot'), [other])
  assert.deepEqual(findOtherBalances([native], 'ugnot'), [])
  assert.ok(page.includes('otherBalances.length > 0'))
  assert.ok(page.includes('otherBalances.map'))
  assert.equal(page.includes('balances.map'), false)
  assert.ok(page.includes('Other balances'))
})
test('page contains account content and all safe result states', () => {
  for (const text of ['Invalid account address', 'Account data is temporarily unavailable', 'Account details are currently unavailable', 'Account not found']) assert.ok(page.includes(text))
  for (const text of ['Balance', 'Raw amount', 'Account number', 'Sequence', 'Technical details', 'Validator', 'No native bank balance', 'Public key not available']) assert.ok(page.includes(text))
  assert.ok(page.includes("primary.display_amount"))
  assert.ok(page.includes("balance.amount"))
  assert.ok(page.includes("new URL(source?.rpc_url).hostname"))
  assert.equal(page.includes('Fetched at block'), false)
})
test('validator operator address links to an encoded account route only when present', () => {
  assert.ok(validator.includes('href={validator.operator_address ? `/accounts/${encodeURIComponent(validator.operator_address)}` : undefined}'))
  assert.ok(validator.includes('className="validator-detail__account-link"'))
  for (const selector of ['.validator-detail__account-link {', '.validator-detail__account-link:hover', '.validator-detail__account-link:focus-visible']) assert.ok(styles.includes(selector))
})
