import assert from 'node:assert/strict'
import fs from 'node:fs'
import test from 'node:test'
const page = fs.readFileSync(new URL('../src/pages/CosmosValidatorDetail.jsx', import.meta.url), 'utf8')
const app = fs.readFileSync(new URL('../src/App.jsx', import.meta.url), 'utf8')
const list = fs.readFileSync(new URL('../src/pages/CosmosValidators.jsx', import.meta.url), 'utf8')
const css = fs.readFileSync(new URL('../src/styles/app.css', import.meta.url), 'utf8')
const detailCss = fs.readFileSync(new URL('../src/styles/cosmos-validator-detail.css', import.meta.url), 'utf8')
const stylesDirectory = new URL('../src/styles/', import.meta.url)
const allStyles = fs.readdirSync(stylesDirectory).filter((name) => name.endsWith('.css')).map((name) => fs.readFileSync(new URL(name, stylesDirectory), 'utf8')).join('\n')

test('Cosmos validator detail route and independent list identity link are present', () => {
  assert.match(app, /CosmosValidatorDetail network=\{network\} operatorAddress=\{cosmosMatch\[3\]\}/)
  assert.match(list, /CosmosValidatorIdentity[^>]+href=\{`\/networks\/\$\{network.id\}\/validators\/\$\{encodeURIComponent/)
  assert.match(list, /<button className=\{`validator-favorite[\s\S]+onClick=\{\(\) => toggleFavorite/)
})

test('detail presents validator-only identity, metrics, signing, slashing and economics', () => {
  for (const text of ['Contact', 'Minimum Self Delegation', 'Account Address', 'Consensus Hex Address', 'Jailed', 'Voting Power', 'Stake Share', '≈24h Change', 'Commission', 'Recent finalized participation', 'Protocol slashing window', 'Rewards & Commission', 'Validator Commission', 'Rewards', 'Consensus Identity', 'Consensus Public Key', 'Delegator Shares']) assert.match(page, new RegExp(text))
  assert.match(page, /Recent 50-block canonical signing panel/)
  assert.match(page, /signingPointLabel\(p\)/)
  assert.match(page, /index === strip\.length - 1 \? ' is-latest'/)
  assert.match(page, /title=\{pointLabel\}/)
  assert.match(page, /CopyButton value=\{value\}/)
  for (const forbidden of ['Delegate', 'Undelegate', 'Withdraw rewards', 'wallet connection']) assert.doesNotMatch(page, new RegExp(forbidden, 'i'))
  assert.match(page, /theme-compatible/)
  assert.match(css, /var\(--color-card\)/)
  assert.match(page, /Past #\{oldestPoint\.height\.toLocaleString\(\)\}/)
  assert.match(page, /Latest finalized #\{newestPoint\.height\.toLocaleString\(\)\}/)
  assert.match(detailCss, /grid-template-columns:\s*repeat\(25, minmax\(0, 1fr\)\)/)
  assert.match(detailCss, /signing__mini-metrics,[\s\S]*signing__monitor[\s\S]*width:\s*min\(100%, 500px\)/)
  assert.match(detailCss, /span\.is-latest/)
  assert.match(detailCss, /grid-template-columns:\s*repeat\(2, minmax\(0, 1fr\)\)/)
  assert.doesNotMatch(allStyles, /minmax\(0, 1\.12fr\) minmax\(0, \.88fr\)/)
  assert.match(detailCss, /align-items:\s*stretch/)
  assert.match(css, /\.cosmos-validator-hero__main \.cosmos-validator-avatar\s*\{[^}]*width:\s*86px/)
  assert.match(css, /\.cosmos-validator-hero__main \.cosmos-validator-avatar\s*\{[^}]*border-radius:\s*11px/)
  assert.match(page, /cosmos-validator-hero__metrics/)
  assert.doesNotMatch(page, /cosmos-validator-detail__metrics/)
  assert.match(page, /fullAddress metadata=\{v\.identity\} action=/)
  assert.doesNotMatch(page, /Field label="Identity"/)
  assert.match(page, /className="cosmos-back block-detail__back"/)
  assert.match(page, /minimumSelfDelegation\(v\.min_self_delegation, asset\)/)
  assert.match(page, /formatSignedTokenAmount\(v\.change_24h, asset\.exponent, asset\.symbol\)/)
  assert.doesNotMatch(page, /v\.change_24h_percent/)
  assert.ok(page.indexOf('cosmos-validator-hero__description') > page.indexOf('cosmos-validator-hero__metrics'))
  assert.match(page, /hero__facts"><Field label="Rank"[\s\S]*Field label="Commission"/)
  assert.match(page, /hero__metrics"><Metric label="Voting Power"[\s\S]*Metric label="Minimum Self Delegation"/)
  assert.match(page, /cosmos-validator-detail__primary[\s\S]*Signing &amp; Liveness[\s\S]*Panel title="Consensus Identity"/)
  assert.match(page, /Panel title="Rewards & Commission"[\s\S]*Panel title="Validator Economics"/)
  assert.match(page, /Address label="Account Address" value=\{v\.account_address\} accent/)
  assert.doesNotMatch(page, /Address label="Account Address"[^>]+href=/)
  assert.match(css, /\.cosmos-validator-address\.is-accent code\s*\{\s*color:\s*var\(--color-accent\)/)
  assert.match(page, /<Address label="EVM Address" value=\{v\.evm_address\} \/>/)
  assert.doesNotMatch(page, /v\.evm_address && <Address label="EVM Address"/)
  assert.match(page, /compactShares\(String\(value\)\)/)
  assert.match(page, /Internal staking shares used by the Cosmos staking module\. They are not token units\./)
  assert.match(page, /CopyButton value=\{String\(value\)\} label="delegator shares"/)
  assert.match(page, /v\.commission_rewards\?\.length/)
  assert.match(page, /v\.outstanding_rewards\?\.length/)
  assert.match(page, /rows\.slice\(0, 4\)/)
  assert.match(page, /label: 'Validator Commission'/)
  assert.match(page, /label: 'Rewards'/)
  assert.doesNotMatch(page, /Outstanding Rewards/)
  assert.match(page, /Show \$\{remaining\} more ↓/)
  assert.match(page, /expanded \? 'Show less ↑'/)
  assert.match(page, /remaining > 0 && <div className="cosmos-validator-rewards__more"/)
  assert.match(page, /assets\.find\(\(item\) => item\.base === coin\.denom\)/)
  assert.match(page, /: `\$\{readableDecimal\(coin\.amount\)\} \$\{coin\.denom\}`/)
  assert.match(detailCss, /grid-template-columns:\s*minmax\(0, 1fr\) 25px/)
  assert.match(detailCss, /grid-auto-rows:\s*max-content/)
  assert.match(page, /previousLatestHeight = useRef\(null\)/)
  assert.match(page, /p\.height === animatedHeight \? ' is-new'/)
  assert.match(page, /newestPoint\.height === animatedHeight/)
  assert.match(page, /window\.setTimeout[\s\S]*1800/)
  assert.match(detailCss, /animation:\s*cosmos-validator-new-point/)
  assert.match(detailCss, /animation:\s*cosmos-validator-new-height/)
  assert.match(detailCss, /prefers-reduced-motion:\s*reduce/)
  assert.match(detailCss, /@media \(max-width: 960px\)[\s\S]*cosmos-validator-detail__primary,[\s\S]*grid-template-columns: 1fr/)
  assert.match(page, /MetaIcon type="website"/)
  assert.match(page, /MetaIcon type="contact"/)
})

test('missed counters reuse the shared semantic threshold class', () => {
  const overview = fs.readFileSync(new URL('../src/pages/CosmosOverview.jsx', import.meta.url), 'utf8')
  assert.match(overview, /className=\{missedCountClass\(row\.missed_blocks_counter\)\}/)
  assert.match(page, /className=\{missedCountClass\(v\.liveness\.missed_blocks\)\}/)
})

test('validator identities link consistently across Cosmos explorer surfaces', () => {
  const files = ['CosmosOverview.jsx', 'CosmosBlocks.jsx', 'CosmosBlockDetail.jsx']
  for (const file of files) {
    const source = fs.readFileSync(new URL(`../src/pages/${file}`, import.meta.url), 'utf8')
    assert.match(source, /CosmosValidatorIdentity[\s\S]*?href=\{/)
    assert.match(source, /\/networks\/\$\{network.id\}\/validators/)
  }
})

test('shared validator identity owns one semantic color contract', () => {
  assert.match(css, /\.cosmos-validator strong\s*\{\s*color:\s*var\(--color-text-bright\)/)
  assert.match(css, /\.cosmos-validator > span\s*\{\s*color:\s*var\(--color-text-secondary\)/)
  assert.match(css, /\.cosmos-validator-identity-link:hover \.cosmos-validator strong,[\s\S]*?focus-visible \.cosmos-validator strong\s*\{\s*color:\s*var\(--color-accent\)/)
  assert.match(css, /\.cosmos-validator-identity-link:focus-visible\s*\{[^}]*outline:\s*2px solid var\(--color-accent\)/)
  assert.doesNotMatch(css, /\.cosmos-blocks \.cosmos-validator strong\s*\{[^}]*color:/)
  assert.doesNotMatch(css, /\.cosmos-validator-hero__main \.cosmos-validator strong\s*\{[^}]*color:/)
})
