"""Read-only Gno governance discovery."""

from .gno import (
    DEFAULT_REALM,
    MAX_GOVERNANCE_PAGES,
    MAX_GOVERNANCE_PROPOSALS,
    GovernanceDiscovery,
    GovernanceListDiscovery,
    GovernanceParseError,
    GovernanceProposalDetail,
    GovernanceProposalSummary,
    GovernanceSource,
    GovernanceVote,
    discover_governance,
    discover_governance_list,
    discover_governance_proposal,
    pager_paths,
    parse_detail,
    parse_proposal_list,
    parse_votes,
)

__all__ = [
    "DEFAULT_REALM",
    "MAX_GOVERNANCE_PAGES",
    "MAX_GOVERNANCE_PROPOSALS",
    "GovernanceDiscovery",
    "GovernanceListDiscovery",
    "GovernanceParseError",
    "GovernanceProposalDetail",
    "GovernanceProposalSummary",
    "GovernanceSource",
    "GovernanceVote",
    "discover_governance",
    "discover_governance_list",
    "discover_governance_proposal",
    "pager_paths",
    "parse_detail",
    "parse_proposal_list",
    "parse_votes",
]
